import './globals.css'
import UserContextProvider from '@/context/userContext'
import { ToastContainer } from 'react-toastify'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='mytheme' >
      
      <body>
        <UserContextProvider>
          {children}
          <ToastContainer autoClose={3000} />
        </UserContextProvider>
      </body>
    </html>
  )
}
