import "./globals.css"
import SideBar from "@/components/(admin)/Shared/SideBar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='mytheme'>
      <body className="bg-primary flex md:flex-row flex-col gap-8">
        {/* Sidebar with fixed width */}
        <aside className="w-44 flex-shrink-0">
          <SideBar />
        </aside>
        
        <main className="flex-1 min-w-0 mx-4 ">
          {children}
        </main>
      </body>
    </html>
  )
}
