import "./globals.css"
import SideBar from "@/components/(admin)/Shared/SideBar"
import { ToastContainer } from "react-toastify"
import { cookies } from "next/headers"
import { redirect } from "next/navigation"
import jwt from'jsonwebtoken'
import GeneralContextProvider from "@/context/generalContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;

  if(!token){
    redirect('/login')
  }

  try {
    const decoded = jwt.verify(token, process.env.SECRET_JWT_TOKEN)
    const {role} = decoded

    if(role !== 'admin'){
      redirect('/login')
    }
  } catch (error) {
    console.error(error)
    redirect('/login')
  }

  return (
    <html lang="en" data-theme='mytheme'>
      <body className="bg-primary flex md:flex-row flex-col gap-8">
        {/* Sidebar with fixed width */}
        <GeneralContextProvider>
          <aside className="w-44 flex-shrink-0">
            <SideBar />
          </aside>
        
          <main className="flex-1 min-w-0 mx-4 ">
            {children}
          </main>
          <ToastContainer autoClose={3000} />
        </GeneralContextProvider>
      </body>
    </html>
  )
}
