import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Shared/NavBar";
import Footer from "@/components/Shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, url }) {
  return (
    <html lang="en" data-theme='mytheme' >
      <body
        
        className={`${geistSans.variable} ${geistMono.variable} bg-primary antialiased `}
      >
        
        <div className="mx-7 md:mx-12 lg:px-32">
          <NavBar />
          {children}
        </div>
        
        <Footer />
      </body>
    </html>
  );
}
